//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Freya.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IFreyaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class FreyaBaseListener : IFreyaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.codeParse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodeParse([NotNull] FreyaParser.CodeParseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.codeParse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodeParse([NotNull] FreyaParser.CodeParseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] FreyaParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] FreyaParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.scriptDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScriptDef([NotNull] FreyaParser.ScriptDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.scriptDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScriptDef([NotNull] FreyaParser.ScriptDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.scriptInit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScriptInit([NotNull] FreyaParser.ScriptInitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.scriptInit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScriptInit([NotNull] FreyaParser.ScriptInitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComment([NotNull] FreyaParser.CommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComment([NotNull] FreyaParser.CommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction([NotNull] FreyaParser.InstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction([NotNull] FreyaParser.InstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] FreyaParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] FreyaParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentList([NotNull] FreyaParser.ArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentList([NotNull] FreyaParser.ArgumentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] FreyaParser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] FreyaParser.ArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.stringLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringLiteral([NotNull] FreyaParser.StringLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.stringLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringLiteral([NotNull] FreyaParser.StringLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.variableDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDef([NotNull] FreyaParser.VariableDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.variableDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDef([NotNull] FreyaParser.VariableDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.typeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeLiteral([NotNull] FreyaParser.TypeLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.typeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeLiteral([NotNull] FreyaParser.TypeLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ValueExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueExpr([NotNull] FreyaParser.ValueExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ValueExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueExpr([NotNull] FreyaParser.ValueExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulDivExpr([NotNull] FreyaParser.MulDivExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulDivExpr([NotNull] FreyaParser.MulDivExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IdExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdExpr([NotNull] FreyaParser.IdExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IdExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdExpr([NotNull] FreyaParser.IdExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenExpr([NotNull] FreyaParser.ParenExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenExpr([NotNull] FreyaParser.ParenExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddSubExpr([NotNull] FreyaParser.AddSubExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddSubExpr([NotNull] FreyaParser.AddSubExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>intValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntValue([NotNull] FreyaParser.IntValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>intValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntValue([NotNull] FreyaParser.IntValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>floatValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatValue([NotNull] FreyaParser.FloatValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>floatValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatValue([NotNull] FreyaParser.FloatValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>stringDoubleValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringDoubleValue([NotNull] FreyaParser.StringDoubleValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>stringDoubleValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringDoubleValue([NotNull] FreyaParser.StringDoubleValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>stringSingleValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringSingleValue([NotNull] FreyaParser.StringSingleValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>stringSingleValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringSingleValue([NotNull] FreyaParser.StringSingleValueContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
