//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Freya.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="FreyaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IFreyaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.codeParse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeParse([NotNull] FreyaParser.CodeParseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.codeParse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeParse([NotNull] FreyaParser.CodeParseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] FreyaParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] FreyaParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.scriptDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScriptDef([NotNull] FreyaParser.ScriptDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.scriptDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScriptDef([NotNull] FreyaParser.ScriptDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.scriptInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScriptInit([NotNull] FreyaParser.ScriptInitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.scriptInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScriptInit([NotNull] FreyaParser.ScriptInitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] FreyaParser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] FreyaParser.CommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] FreyaParser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] FreyaParser.InstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] FreyaParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] FreyaParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentList([NotNull] FreyaParser.ArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentList([NotNull] FreyaParser.ArgumentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument([NotNull] FreyaParser.ArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument([NotNull] FreyaParser.ArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringLiteral([NotNull] FreyaParser.StringLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringLiteral([NotNull] FreyaParser.StringLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.variableDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDef([NotNull] FreyaParser.VariableDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.variableDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDef([NotNull] FreyaParser.VariableDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FreyaParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeLiteral([NotNull] FreyaParser.TypeLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FreyaParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeLiteral([NotNull] FreyaParser.TypeLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ValueExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueExpr([NotNull] FreyaParser.ValueExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ValueExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueExpr([NotNull] FreyaParser.ValueExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulDivExpr([NotNull] FreyaParser.MulDivExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulDivExpr([NotNull] FreyaParser.MulDivExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IdExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdExpr([NotNull] FreyaParser.IdExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IdExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdExpr([NotNull] FreyaParser.IdExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenExpr([NotNull] FreyaParser.ParenExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenExpr([NotNull] FreyaParser.ParenExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddSubExpr([NotNull] FreyaParser.AddSubExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddSubExpr([NotNull] FreyaParser.AddSubExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>intValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntValue([NotNull] FreyaParser.IntValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>intValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntValue([NotNull] FreyaParser.IntValueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>floatValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloatValue([NotNull] FreyaParser.FloatValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>floatValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloatValue([NotNull] FreyaParser.FloatValueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stringDoubleValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringDoubleValue([NotNull] FreyaParser.StringDoubleValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stringDoubleValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringDoubleValue([NotNull] FreyaParser.StringDoubleValueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stringSingleValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringSingleValue([NotNull] FreyaParser.StringSingleValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stringSingleValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringSingleValue([NotNull] FreyaParser.StringSingleValueContext context);
}
