//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Freya.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FreyaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IFreyaVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FreyaParser.codeParse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodeParse([NotNull] FreyaParser.CodeParseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FreyaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] FreyaParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FreyaParser.scriptDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScriptDef([NotNull] FreyaParser.ScriptDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FreyaParser.scriptInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScriptInit([NotNull] FreyaParser.ScriptInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FreyaParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComment([NotNull] FreyaParser.CommentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FreyaParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction([NotNull] FreyaParser.InstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FreyaParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] FreyaParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FreyaParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentList([NotNull] FreyaParser.ArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FreyaParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] FreyaParser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FreyaParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringLiteral([NotNull] FreyaParser.StringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FreyaParser.variableDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDef([NotNull] FreyaParser.VariableDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FreyaParser.typeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeLiteral([NotNull] FreyaParser.TypeLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ValueExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueExpr([NotNull] FreyaParser.ValueExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulDivExpr([NotNull] FreyaParser.MulDivExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IdExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdExpr([NotNull] FreyaParser.IdExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenExpr([NotNull] FreyaParser.ParenExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="FreyaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddSubExpr([NotNull] FreyaParser.AddSubExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>intValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntValue([NotNull] FreyaParser.IntValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>floatValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatValue([NotNull] FreyaParser.FloatValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stringDoubleValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringDoubleValue([NotNull] FreyaParser.StringDoubleValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stringSingleValue</c>
	/// labeled alternative in <see cref="FreyaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringSingleValue([NotNull] FreyaParser.StringSingleValueContext context);
}
